ALTER TABLE "Product"
ADD COLUMN IF NOT EXISTS "promotedAdPercent" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "Variant"
ADD COLUMN IF NOT EXISTS "promotedAdPercent" DOUBLE PRECISION NOT NULL DEFAULT 0;
