ALTER TYPE "EbayImportJobStatus" ADD VALUE IF NOT EXISTS 'PAUSING';
ALTER TYPE "EbayImportJobStatus" ADD VALUE IF NOT EXISTS 'PAUSED';
ALTER TYPE "EbayImportJobStatus" ADD VALUE IF NOT EXISTS 'CANCELLING';
ALTER TYPE "EbayImportJobStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';

ALTER TABLE "EbayImportJob"
  ADD COLUMN IF NOT EXISTS "selectedListingIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "completedListingIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS "pausedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "cancelledAt" TIMESTAMP(3);
