ALTER TYPE "EbayImportJobStatus" ADD VALUE IF NOT EXISTS 'PAUSING';
ALTER TYPE "EbayImportJobStatus" ADD VALUE IF NOT EXISTS 'PAUSED';
ALTER TYPE "EbayImportJobStatus" ADD VALUE IF NOT EXISTS 'CANCELLING';
ALTER TYPE "EbayImportJobStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';

ALTER TABLE "EbayImportJob"
  ADD COLUMN "selectedListingIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "completedListingIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN "pausedAt" TIMESTAMP(3),
  ADD COLUMN "cancelledAt" TIMESTAMP(3);
